language: node_js
node_js: node
script:
  - npm test
after_success:
  - bash deploy_doc.sh

deploy:
  provider: npm
  email: grumpy.chat.wane@gmail.com
  api_key: $NPM
  on:
    tags: true
    repo: Chat-Wane/LSEQTree
notifications:
  email: false
